### ISSUE TITLE
closing animation

### ISSUE THREAD

**Issue by BananaAcid** [valnub/Framework7-Plugin-Welcomescreen#44]
How can a closing animation be added by using the close button?

`onClose` is not available ..

**Comment by valnub** [comment]
It is called `onClosed`, not `onClose`

**Comment by BananaAcid** [comment]
You probably misunderstood me: I know that `onClosed` is AVAILABLE, but a `onClose` or `beforeClose` is not - for having us do a closing animation.

**Comment by valnub** [comment]
Ah, I see. Currently this is not possible with this plugin because the swiper container gets completely removed onClose: https://github.com/valnub/Framework7-Plugin-Welcomescreen/blob/master/src/f7.welcomescreen.js#L169

In order to achieve what you want this would have to be changed the way that the container stays and the opacity gets reduced to 0 with a css3 transition.
